Repository project-porko/porko-service, pull requests merged in 2024-06, with the labels that each got.

#77 refactor:(#74): 불필요 step 제거
  Dockerfile
Labels: build, refactor

#79 ci: add GitHub actions test flow with submodule
  .github/workflows/test-reporter.yml
  .gitmodules
  porko-common/build.gradle.kts
  porko-service/build.gradle.kts
Labels: build, ci

#84 feat: API Docs 제공을 위한 Swagger 적용
  porko-service/build.gradle.kts
  porko-service/src/main/java/io/porko/auth/config/SecurityConfig.java
  porko-service/src/main/java/io/porko/config/swagger/SwaggerConfig.java
  porko-service/src/main/java/io/porko/member/controller/MemberController.java
  porko-service/src/main/java/io/porko/widget/controller/MemberWidgetController.java
  porko-service/src/main/java/io/porko/widget/controller/WidgetController.java
Labels: build, feat, config

#82 Feature/#29 history
  porko-service/src/main/java/io/porko/history/controller/HistoryController.java
  porko-service/src/main/java/io/porko/history/controller/model/HistoryResponse.java
  porko-service/src/main/java/io/porko/history/domain/History.java
  porko-service/src/main/java/io/porko/history/domain/SpendingCategory.java
  porko-service/src/main/java/io/porko/history/domain/TransactionType.java
  porko-service/src/main/java/io/porko/history/repo/HistoryRepo.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
  porko-service/src/main/resources/data.sql
Labels: feat

#85 fix: fix to not matching member type in history query repo
  porko-service/src/main/java/io/porko/history/repo/HistoryQueryRepo.java
Labels: fix

#86 fix: github actions에서 발생하는 실패 테스트 제외
  .github/workflows/pr-test-reporter.yml
  porko-service/src/test/java/io/porko/auth/controller/AuthControllerTest.java
  porko-service/src/test/java/io/porko/member/controller/MemberControllerTest.java
Labels: fix, build, test

#80 Feat: 소비 관련 enum 클래스 구현
  porko-service/src/main/java/io/porko/consumption/domain/RegretItem.java
  porko-service/src/main/java/io/porko/consumption/domain/Weather.java
Labels: feat

#87 refactor: Exception 처리를 위한 오류 메세지 가공 부 중복 제거
  porko-common/src/main/java/io/porko/exception/BusinessException.java
  porko-service/src/main/java/io/porko/auth/exception/AuthErrorCode.java
  porko-service/src/main/java/io/porko/auth/exception/AuthException.java
  porko-service/src/main/java/io/porko/budget/exception/BudgetErrorCode.java
  porko-service/src/main/java/io/porko/budget/exception/BudgetException.java
  porko-service/src/main/java/io/porko/member/exception/MemberErrorCode.java
  porko-service/src/main/java/io/porko/member/exception/MemberException.java
  porko-service/src/main/java/io/porko/widget/controller/model/ReorderWidgetRequest.java
  porko-service/src/main/java/io/porko/widget/exception/WidgetException.java
  porko-service/src/test/java/io/porko/auth/domain/TokenResolverTest.java
  porko-service/src/test/java/io/porko/member/facade/dto/ValidateDuplicateTypeTest.java
  porko-service/src/test/java/io/porko/member/service/MemberServiceTest.java
  porko-service/src/test/java/io/porko/widget/controller/WidgetControllerTest.java
  porko-service/src/test/java/io/porko/widget/controller/model/ModifyMemberWidgetOrderDtoTest.java
  porko-service/src/test/java/io/porko/widget/controller/model/ReorderWidgetRequestTest.java
  porko-service/src/test/java/io/porko/widget/domain/OrderedMemberWidgetsTest.java
Labels: refactor

#106 fix: 에러 발생 시 디버깅을 위한 에러 객체 출력 부 추가
  porko-common/src/main/java/io/porko/exception/handler/BaseExceptionHandler.java
  porko-common/src/main/java/io/porko/exception/response/ErrorResponse.java
  porko-service/src/main/resources/application-service.yml
Labels: fix

#116 fix(#115): ExceptionHandler 분리로 인해 예상하지 못한 ExceptionHandler 동작 오류 수정
  porko-common/src/main/java/io/porko/exception/handler/BaseExceptionHandler.java
  porko-common/src/main/java/io/porko/exception/handler/UnexpectedExceptionHandler.java
Labels: fix

#122 feat: 사용자 위젯 조회 및 순서 변경 API 수정
  porko-service/src/main/java/io/porko/widget/controller/MemberWidgetController.java
  porko-service/src/main/java/io/porko/widget/controller/model/MemberWidgetsResponse.java
  porko-service/src/main/java/io/porko/widget/controller/model/ModifyMemberWidgetOrderDto.java
  porko-service/src/main/java/io/porko/widget/controller/model/OrderedMemberWidgetsResponse.java
  porko-service/src/main/java/io/porko/widget/controller/model/ReorderWidgetRequest.java
  porko-service/src/main/java/io/porko/widget/controller/model/UnorderedMemberWidgetsDto.java
  porko-service/src/main/java/io/porko/widget/controller/model/WidgetsResponse.java
  porko-service/src/main/java/io/porko/widget/domain/MemberWidget.java
  porko-service/src/main/java/io/porko/widget/domain/MemberWidgets.java
  porko-service/src/main/java/io/porko/widget/domain/ReOrderedMemberWidgets.java
  porko-service/src/main/java/io/porko/widget/domain/Sequence.java
  porko-service/src/main/java/io/porko/widget/domain/Widget.java
  porko-service/src/main/java/io/porko/widget/domain/WidgetCode.java
  porko-service/src/main/java/io/porko/widget/domain/WidgetType.java
  porko-service/src/main/java/io/porko/widget/exception/WidgetErrorCode.java
  porko-service/src/main/java/io/porko/widget/repo/MemberWidgetRepo.java
  porko-service/src/main/java/io/porko/widget/service/MemberWidgetService.java
  porko-service/src/main/resources/data.sql
  porko-service/src/test/java/io/porko/auth/controller/AuthControllerTest.java
  porko-service/src/test/java/io/porko/auth/domain/TokenProviderTest.java
  porko-service/src/test/java/io/porko/auth/domain/TokenResolverTest.java
  porko-service/src/test/java/io/porko/config/security/TestSecurityConfig.java
  porko-service/src/test/java/io/porko/member/controller/MemberControllerTest.java
  porko-service/src/test/java/io/porko/widget/controller/MemberWidgetControllerTest.java
  porko-service/src/test/java/io/porko/widget/controller/WidgetControllerTestHelper.java
  porko-service/src/test/java/io/porko/widget/controller/model/ReorderWidgetRequestTest.java
  porko-service/src/test/java/io/porko/widget/domain/ReOrderedMemberWidgetsTest.java
  porko-service/src/test/java/io/porko/widget/domain/SequenceTest.java
  porko-service/src/test/java/io/porko/widget/fixture/MemberWidgetFixture.java
  porko-service/src/test/java/io/porko/widget/service/MemberWidgetServiceTest.java
Labels: fix, chore, refactor

#123 fix(#120): 원시타입 포장객체 컬럼명 미 지정으로 인한 오류 수정
  porko-service/src/main/java/io/porko/widget/domain/MemberWidget.java
Labels: fix

#126 feat: 회원 프로필 이미지 저장을 위한 필드 추가
  porko-service/src/main/java/io/porko/member/controller/MemberController.java
  porko-service/src/main/java/io/porko/member/controller/model/MemberResponse.java
  porko-service/src/main/java/io/porko/member/controller/model/signup/SignUpRequest.java
  porko-service/src/main/java/io/porko/member/domain/Member.java
  porko-service/src/main/java/io/porko/member/repo/MemberQueryRepo.java
  porko-service/src/main/resources/data.sql
  porko-service/src/test/java/io/porko/config/security/TestSecurityConfig.java
  porko-service/src/test/java/io/porko/member/controller/MemberControllerTestHelper.java
  porko-service/src/test/java/io/porko/member/repo/MemberRepoTest.java
Labels: feat

#127 feat: 로그인 응답 필드에 회원 프로필 이미지 주소 추가
  porko-service/src/main/java/io/porko/auth/controller/AuthController.java
  porko-service/src/main/java/io/porko/auth/controller/model/LoginResponse.java
  porko-service/src/main/java/io/porko/auth/service/AuthService.java
  porko-service/src/main/resources/data.sql
  porko-service/src/test/java/io/porko/auth/controller/AuthControllerTest.java
Labels: feat

#131 feat: 캘린더 일별 데이터 조회 API 구현
  porko-service/src/main/java/io/porko/consumption/domain/Weather.java
  porko-service/src/main/java/io/porko/history/controller/HistoryController.java
  porko-service/src/main/java/io/porko/history/controller/model/CalendarResponse.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
Labels: feat

#135 chore: 테스트 회원 위젯 목록 더미 데이터 SQL 추가
  porko-service/src/main/resources/data.sql
Labels: chore

#133 feat: 신규 회원의 위젯 생성 Event 처리
  porko-service/src/main/java/io/porko/PorkoServiceApp.java
  porko-service/src/main/java/io/porko/event/DomainEvent.java
  porko-service/src/main/java/io/porko/event/DomainEventPublisher.java
  porko-service/src/main/java/io/porko/event/DomainEventPublisherAspect.java
  porko-service/src/main/java/io/porko/member/event/CreateInitialMemberWidgetsEvent.java
  porko-service/src/main/java/io/porko/member/service/MemberService.java
  porko-service/src/main/java/io/porko/widget/domain/MemberWidget.java
  porko-service/src/main/java/io/porko/widget/domain/MemberWidgets.java
  porko-service/src/main/java/io/porko/widget/domain/Widget.java
  porko-service/src/main/java/io/porko/widget/domain/WidgetCode.java
  porko-service/src/main/java/io/porko/widget/domain/Widgets.java
  porko-service/src/main/java/io/porko/widget/event/CreateInitialMemberWidgetsEventListener.java
  porko-service/src/test/java/io/porko/widget/domain/MemberWidgetsTest.java
  porko-service/src/test/java/io/porko/widget/event/CreateInitialMemberWidgetsEventListenerTest.java
Labels: feat

#137 feat: 소비 날씨, 후회 아이템 enum 클래스 수정
  porko-service/src/main/java/io/porko/consumption/domain/RegretItem.java
  porko-service/src/main/java/io/porko/consumption/domain/Weather.java
  porko-service/src/main/java/io/porko/history/controller/model/CalendarResponse.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
Labels: chore

#139 feat: 하루 예산 대비 지출 금액에 따른 사용률 계산 기능 구현
  porko-service/src/main/java/io/porko/budget/service/BudgetService.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
  porko-service/src/main/resources/data.sql
Labels: fix

#143 feat: csv 금융 거래 기록 파싱 및 SpringContextLoad 시점에 금융 거래 기록 저장
  .gitignore
  porko-common/build.gradle.kts
  porko-service/build.gradle.kts
  porko-service/src/main/java/io/porko/account/csv/CsvBean.java
  porko-service/src/main/java/io/porko/account/csv/CsvToJavaBeansConverter.java
  porko-service/src/main/java/io/porko/account/csv/TransactionRecordCsvBean.java
  porko-service/src/main/java/io/porko/account/csv/TransactionRecordCsvBeans.java
  porko-service/src/main/java/io/porko/account/domain/AccountHolder.java
  porko-service/src/main/java/io/porko/account/domain/AccountTransaction.java
  porko-service/src/main/java/io/porko/account/domain/AccountTransactions.java
  porko-service/src/main/java/io/porko/account/domain/TransactionCategory.java
  porko-service/src/main/java/io/porko/account/domain/TransactionRecord.java
  porko-service/src/main/java/io/porko/account/domain/TransactionType.java
  porko-service/src/main/java/io/porko/account/event/InitializeDataEventListener.java
  porko-service/src/main/java/io/porko/account/repo/AccountHolderRepo.java
  porko-service/src/main/java/io/porko/account/repo/TransactionRecordRepo.java
  porko-service/src/test/java/io/porko/account/domain/CsvToJavaBeansConverterTest.java
  porko-service/src/test/java/io/porko/account/event/InitializeDataEventListenerTest.java
  porko-service/src/test/java/io/porko/account/repo/TransactionRecordRepoTest.java
  porko-service/src/test/java/io/porko/widget/event/CreateInitialMemberWidgetsEventListenerTest.java
Labels: build, feat, refactor, config, test

#142 feat: 공유 멤버 API 구현
  porko-service/src/main/java/io/porko/friend/controller/FriendController.java
  porko-service/src/main/java/io/porko/friend/controller/model/FriendResponse.java
  porko-service/src/main/java/io/porko/friend/domain/Friend.java
  porko-service/src/main/java/io/porko/friend/domain/FriendId.java
  porko-service/src/main/java/io/porko/friend/repo/FriendRepo.java
  porko-service/src/main/java/io/porko/friend/service/FriendService.java
  porko-service/src/main/resources/data.sql
Labels: feat

#145 feat: 목표 예산에 따른 캘린더 소비 날씨 처리
  porko-service/src/main/java/io/porko/budget/service/BudgetService.java
  porko-service/src/main/java/io/porko/consumption/domain/Weather.java
  porko-service/src/main/java/io/porko/history/controller/model/CalendarResponse.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
Labels: feat

#148 feat: 쓰고 후회한 돈 API 구현
  porko-service/src/main/java/io/porko/consumption/controller/ConsumptionController.java
  porko-service/src/main/java/io/porko/consumption/controller/model/RegretResponse.java
  porko-service/src/main/java/io/porko/consumption/domain/RegretItem.java
  porko-service/src/main/java/io/porko/consumption/service/ConsumptionService.java
  porko-service/src/main/java/io/porko/history/repo/HistoryQueryRepo.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
  porko-service/src/main/resources/data.sql
Labels: feat

#149 feat: 공유 멤버 조회시 멤버 수 조회 기능 추가 구현
  porko-service/src/main/java/io/porko/friend/controller/FriendController.java
  porko-service/src/main/java/io/porko/friend/controller/model/FriendList.java
  porko-service/src/main/java/io/porko/friend/controller/model/FriendResponse.java
  porko-service/src/main/java/io/porko/friend/service/FriendService.java
Labels: feat

#151 Feature/#136 sign up complete save transaction record event
  Dockerfile
  porko-service/src/main/java/io/porko/account/domain/AccountHolder.java
  porko-service/src/main/java/io/porko/account/domain/TransactionRecord.java
  porko-service/src/main/java/io/porko/account/domain/TransactionType.java
  porko-service/src/main/java/io/porko/account/repo/TransactionRecordRepo.java
  porko-service/src/main/java/io/porko/config/event/DomainEvent.java
  porko-service/src/main/java/io/porko/config/event/DomainEventPublisher.java
  porko-service/src/main/java/io/porko/config/event/DomainEventPublisherAspect.java
  porko-service/src/main/java/io/porko/history/domain/ExpenseCategory.java
  porko-service/src/main/java/io/porko/history/domain/Histories.java
  porko-service/src/main/java/io/porko/history/domain/History.java
  porko-service/src/main/java/io/porko/history/domain/HistoryCategory.java
  porko-service/src/main/java/io/porko/history/event/CreateHistoriesEventListener.java
  porko-service/src/main/java/io/porko/history/exception/HistoryErrorCode.java
  porko-service/src/main/java/io/porko/member/event/CreateHistoriesEvent.java
  porko-service/src/main/java/io/porko/member/event/CreateInitialMemberWidgetsEvent.java
  porko-service/src/main/java/io/porko/member/service/MemberService.java
  porko-service/src/test/java/io/porko/account/repo/TransactionRecordRepoTest.java
  porko-service/src/test/java/io/porko/history/domain/ExpenseCategoryTest.java
Labels: feat, test

#156 feat: 공유 멤버 조회시 멤버 수 조회 기능 추가 구현
  porko-service/src/main/java/io/porko/friend/service/FriendService.java
  porko-service/src/main/resources/data.sql
Labels: chore, feat

#159 feat: 페이징 처리를 위한 설정 추가
  porko-common/src/main/java/io/porko/pagination/config/PaginationArgumentResolver.java
  porko-common/src/main/java/io/porko/pagination/config/WebConfig.java
  porko-common/src/main/java/io/porko/pagination/request/Pagination.java
  porko-common/src/main/java/io/porko/pagination/response/PageResponse.java
Labels: feat, config

#161 feat: 사용자의 입/출금 내역 조회 시 페이징 처리 추가
  porko-common/src/main/java/io/porko/pagination/config/PaginationArgumentResolver.java
  porko-common/src/main/java/io/porko/pagination/response/PageResponse.java
  porko-service/src/main/java/io/porko/history/controller/HistoryController.java
  porko-service/src/main/java/io/porko/history/controller/model/HistoryListResponse.java
  porko-service/src/main/java/io/porko/history/repo/HistoryRepo.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
  porko-service/src/test/java/io/porko/widget/event/CreateInitialMemberWidgetsEventListenerTest.java
Labels: feat

#162 feat: 목표 예산 수정 API 구현
  porko-service/src/main/java/io/porko/budget/controller/BudgetController.java
  porko-service/src/main/java/io/porko/budget/domain/Budget.java
  porko-service/src/main/java/io/porko/budget/service/BudgetService.java
Labels: feat

#164 fix: 목표 예산 조회 API 수정
  porko-service/src/main/java/io/porko/budget/service/BudgetService.java
Labels: fix

#169 test: 더미 데이터 프로필 이미지 확장자 변경
  porko-service/src/main/resources/data.sql
Labels: chore, test

#170 style(#166): data.sql 테스트를 위한 더미데이터 수정
  porko-service/src/main/resources/data.sql
Labels: test

#173 feat: 월별 소비 날씨 통계 API 구현
  porko-service/src/main/java/io/porko/consumption/controller/ConsumptionController.java
  porko-service/src/main/java/io/porko/consumption/controller/model/WeatherListResponse.java
  porko-service/src/main/java/io/porko/consumption/controller/model/WeatherResponse.java
  porko-service/src/main/java/io/porko/consumption/service/ConsumptionService.java
  porko-service/src/main/java/io/porko/history/service/HistoryService.java
Labels: feat

#175 test: 더미 데이터 수정
  porko-service/src/main/resources/data.sql
Labels: test

#176 test: 다른 사용자 지출 데이터 추가
  porko-service/src/main/resources/data.sql
Labels: chore, test

#177 test: 다른 사용자 목표 예산 데이터 추가
  porko-service/src/main/resources/data.sql
Labels: test

#179 feat: 친구 추가 API 구현
  porko-service/src/main/java/io/porko/consumption/controller/model/FriendRequest.java
  porko-service/src/main/java/io/porko/friend/controller/FriendController.java
  porko-service/src/main/java/io/porko/friend/domain/Friend.java
  porko-service/src/main/java/io/porko/friend/service/FriendService.java
  porko-service/src/main/java/io/porko/member/repo/MemberRepo.java
  porko-service/src/main/java/io/porko/member/service/MemberService.java
  porko-service/src/main/resources/data.sql
Labels: feat

#180 test: 목표 예산 특정 더미 데이터 삭제
  porko-service/src/main/resources/data.sql
Labels: test

#181 test: 더미 데이터 추가
  porko-service/src/main/resources/data.sql
Labels: test

#186 init: spring boot admin server
  settings.gradle.kts
  spring-boot-admin/build.gradle.kts
  spring-boot-admin/src/main/java/io/porko/PorkoSpringBootAdminApp.java
  spring-boot-admin/src/main/resources/application.yml
Labels: build, feat, config

#188 fix: 목표 예산 조회시 예산 초과 데이터 조회 수정
  porko-service/src/main/java/io/porko/budget/service/BudgetService.java
  porko-service/src/main/java/io/porko/history/repo/HistoryQueryRepo.java
Labels: fix

#198 refactor: separate web layer and bean based test base class
  porko-service/src/test/java/io/porko/domain/member/facade/ValidateDuplicateFacadeTest.java
  porko-service/src/test/java/io/porko/global/config/base/ServiceBeanTestBase.java
  porko-service/src/test/java/io/porko/global/config/cache/CacheConfigTestHelper.java
Labels: refactor, test
